services:
  my-api:
    container_name: my-api
    image: my-api
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8083:8080
    networks:
      - my-network
      - my-network2

    develop:
      watch:
        - path: bin
          action: rebuild
          target: /app

networks:
  my-network:
    driver: bridge
    name: my-network
  my-network2:
    external: true
